# environment.yml
name: hansard
channels:
  - conda-forge          # gives recent httpx & polars
dependencies:
  # core runtime
  - python=3.12          # pick the latest your Conda supports
  - httpx >=0.27
  - tenacity >=8
  - polars >=0.20
  - pandas >=2
  - numpy >=1.26
  - spacy >=3.7
  - gensim >=4
  - scikit-learn >=1.5
  - matplotlib >=3.8
  - seaborn >=0.13
  - wordcloud >=1.9
  - beautifulsoup4 >=4.12
  - psutil >=5.9
  - python-Levenshtein >=0.25
  - streamlit >=1.35

  # (optional) dev helpers
  - black
  - ruff
  - pytest
  - pytest-asyncio
