# environment.yml
name: hansard
channels:
  - conda-forge          # gives recent httpx & polars
dependencies:
  # core runtime
  - python=3.12          # pick the latest your Conda supports
  - httpx >=0.27
  - tenacity >=8
  - polars >=0.20
  - spacy >=3.7
  - gensim >=4
  - scikit-learn >=1.5
  - streamlit >=1.35
  - gender-guesser >=0.4.0
  - SPARQLWrapper >=2.0.0
  - beautifulsoup4 >=4.13.4


  # (optional) dev helpers
  - black
  - ruff
  - pytest

